# Generated by Django 2.2.17 on 2021-01-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210113_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_details',
            field=models.TextField(default=' sdfds'),
        ),
    ]
