# Generated by Django 2.2.17 on 2021-01-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210113_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_details',
            field=models.DateField(default=' None '),
        ),
    ]
