# Generated by Django 2.2.17 on 2021-01-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20210114_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_details',
            field=models.TextField(default=' None '),
        ),
    ]
