# Generated by Django 2.2.17 on 2021-01-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20210114_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_details',
        ),
        migrations.AddField(
            model_name='project',
            name='project_category',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='project_country',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='project_state',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
