# Generated by Django 2.2.17 on 2021-01-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20210116_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_state',
            new_name='project_status',
        ),
    ]
